name: downstream-dispatch-event

on:
  push:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  dispatch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: dispatch update samples event
        run: sh ./scripts/dispatch-update-samples-event.sh ${{secrets.OKTA_433527}}

        